# Whether or not to enable invisible item frames glowing when there's no item in them
# This will also make them visible when there's no item in them
item-frames-glow: true

itemname-invframe: "Invisible Item Frame"
itemname-glow-invframe: "Glowing Invisible Item Frame"

messages:
  no-access: "§cSorry, you don't have permission to run this command"
  not-player: "§cSorry, you must be a player to use this command!"
  player-not-found: "§cPlayer %player% is not online."
  give-success: "§aAdded an invisible item frame to your inventory"
  reload-success: "§aReloaded!"
  recheck-success: "§aRechecked invisible item frames"
  recipe-update-success: "§aRecipe item updated!"
